waylon/wiki/models.py
# -*- coding: utf-8 -*-
"""Wiki models."""
from datetime import datetime as dt

from waylon.database import Column, CRUDMixin, PkModel, db


class WikiPage(PkModel, CRUDMixin):
    """A wiki page."""

    __tablename__ = "wikis"

    page_name = Column(db.String(80), unique=True, nullable=False)
    page_title = Column(db.String(80), unique=True, nullable=False)
    content = Column(db.Text, nullable=False)
    last_edit = dt.utcnow()

    # def save(self):
    #     """
    #     Save oneself.
    #     """
    #     with db.session.begin():
    #         db.session.add(self)

    def __repr__(self):
        """Represent instance as a unique string."""
        return f"<WikiPage({self.page_name!r})>"

waylon/wiki/forms.py
# -*- coding: utf-8 -*-
"""User forms."""

from flask_wtf import FlaskForm
from wtforms import DateField, StringField, SubmitField
from wtforms.validators import DataRequired
from wtforms.widgets import TextArea

from .models import WikiPage


class WikiPageForm(FlaskForm):
    """Wiki page form."""

    page_name = StringField("Page name", validators=[DataRequired()])
    page_title = StringField("Page title", validators=[DataRequired()])
    content = StringField("Content", widget=TextArea())
    last_edit = DateField("Last edit")
    submit = SubmitField("Save")

    # def __init__(self, *args, **kwargs):
    #     """Create instance."""
    #     super(WikiPageForm, self).__init__(*args, **kwargs)
    #     self.page_name = ""
    #     self.page_title = ""
    #     self.content = ""
    #     self.last_edit = ""

    def validate(self, **kwargs):
        """Validate the form."""

        initial_validation = super(WikiPageForm, self).validate()

        if not initial_validation:
            return False

        page = WikiPage.query.filter_by(page_name=self.page_name.data).first()

        if page:
            self.page_name.errors.append("Page name already exists")

            return False
        page = WikiPage.query.filter_by(page_title=self.page_title.data).first()

        if page:
            self.page_title.errors.append("Page Title already registered")
            return False
        return True

waylon/wiki/__init__.py
# -*- coding: utf-8 -*-
"""The wiki module."""
from . import views  # noqa

waylon/wiki/views.py
# -*- coding: utf-8 -*-
"""Public section, including homepage and signup."""
from datetime import datetime as dt

from flask import Blueprint, flash, redirect, render_template, request, url_for
from markdown_it import MarkdownIt

from .forms import WikiPageForm
from .models import WikiPage

blueprint = Blueprint("wiki", __name__, static_folder="../static", url_prefix="/wiki")


# @login_manager.user_loader
# def load_user(user_id):
#     """Load user by ID."""
#     return User.get_by_id(int(user_id))


@blueprint.route("/", methods=["GET"])
def home():
    """Home page."""
    return redirect(url_for("wiki.page_list", title="Wiki Home Page"))


@blueprint.route("/list", methods=["GET"])
# TODO: change the name of this function to page_list and change all references to the new name
def page_list():
    """Wiki Page List."""
    pages = WikiPage.query.all()
    return render_template("wiki/list.html", title="Wiki Page List", pages=pages)


@blueprint.route("/<page_id>", methods=["GET"])
def view_page(page_id):
    """View page."""
    md = MarkdownIt("gfm-like", {"linkify": False})
    page = WikiPage.query.filter_by(id=page_id).first()
    html = md.render(page.content)
    return render_template("wiki/view.html", title=page.page_name, page=page, html=html)


@blueprint.route("/new_page", methods=["GET", "POST"])
def new_page():
    """New page."""
    page = WikiPage()
    form = WikiPageForm()
    if request.method == "POST":
        if form.validate_on_submit():
            page.page_name = form.page_name.data
            page.page_title = form.page_title.data
            page.content = form.content.data
            page.last_edit = dt.utcnow()
            page.save()
            flash("Page created.", "success")
            return redirect(url_for("wiki.view_page", page_id=page.id))
    return render_template("wiki/new.html", title="New Page", new_page_form=form, page=page)


@blueprint.route("/edit/<page_id>", methods=["GET", "POST"])
def edit_page(page_id):
    """Edit page."""
    page = WikiPage.query.filter_by(id=page_id).first()
    form = WikiPageForm(obj=page)
    if request.method == "POST":
        # if form.validate_on_submit():
        page.page_name = form.page_name.data
        page.page_title = form.page_title.data
        page.content = form.content.data
        page.last_edit = dt.utcnow()
        page.save()
        flash("Page updated.", "success")
        return redirect(url_for("wiki.page_list"))
    return render_template("wiki/edit.html", title="Edit Page", edit_form=form, page=page)


# delete a page
@blueprint.route("/delete/<page_id>", methods=["GET", "POST"])
def delete(page_id):
    """Delete page."""
    page = WikiPage.query.filter_by(id=page_id).first()
    page.delete()
    flash(f"Page {page.page_name} deleted.", "success")
    return redirect(url_for("wiki.page_list", title="IPAM Home"))

waylon/templates/wiki/edit.html
{% extends "layout.html" %}

{% block page_title %}
{{ title }}
{% endblock page_title %}
{% block content %}
<div class="container container-lg pt-3">
    <div class="row justify-content-center align-items-center g-2">
        <div class="col">
            {# TODO: format page #}
            <form action="" method="post">
                {{ edit_form.hidden_tag() }}
                <div class="form-group">
                    {{ edit_form.page_name.label(class="form-label") }}
                    {{ edit_form.page_name(class="form-control ", size=32) }}
                </div>
                <div class="form-group">
                    {{ edit_form.page_title.label(class="form-label") }}
                    {{ edit_form.page_title(class="form-control", size=32) }}
                </div>
                <div class="form-group">
                    {{ edit_form.content.label(class="form-label") }}
                    {{ edit_form.content(class="form-control", rows=15) }}
                </div>
                {{ edit_form.submit(class_="btn btn-primary", method="POST") }}
                <a class="btn btn-secondary" href="{{url_for('wiki.view_page', page_id=edit_form.id)}}"" role="
                    button">Cancel</a>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

waylon/templates/wiki/list.html
{% extends "layout.html" %}
{% block page_title %}
{{ title }}
{% endblock page_title %}
{% block content %}
<div class="container-lg p-3">
    <div class="row-cols-auto justify-content-center align-items-center g-2 mb-3">
        <div class="col">
            <a name="" id="" class="btn btn-primary" href="{{url_for('wiki.new_page')}}" role="button">New</a>
        </div>
    </div>
    <div class="row-cols-auto justify-content-center align-items-center g-2 mt-3">
        <div class="col">
            <div class="table-responsive">
                <table class="table table-primary">
                    <thead>
                        <tr>
                            <th scope="col">Page Name</th>
                            <th scope="col">Page Title</th>
                            <th scope="col">Last Edited</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for page in pages %}
                        <tr class="">
                            <td scope="row"><a
                                    href="{{url_for('wiki.view_page', page_id=page.id)}}">{{page.page_name}}</a></td>
                            <td>{{page.page_title}}</td>
                            <td>{{page.last_edit.strftime("%Y-%m-%d %H:%M")}}</td>
                            {# TODO: remove these links #}
                            {# <td>
                                <a name="" id="" class="btn btn-primary"
                                    href="{{url_for('wiki.edit_page', page_id=page.id)}}" role="button" method="GET">
                                    <i class="bi-pencil"></i>
                                </a>
                                <a name="" id="" class="btn btn-primary"
                                    href="{{url_for('wiki.delete', page_id=page.id)}}" role="button">
                                    <i class="bi-trash"></i>
                                </a>
                            </td> #}
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

waylon/templates/wiki/new.html
{% extends "layout.html" %}
{% block page_title %}{{ title }}{% endblock page_title %}
{% block content %}
<div class="container-lg pt-3">
    <div class="row-cols-auto justify-content-center align-items-center g-2">
        <div class="col">
            <form action="" method="post">
                {{ new_page_form.hidden_tag() }}
                <div class="form-group">
                    {{ new_page_form.page_name.label }}
                    {{ new_page_form.page_name(class_="form-control", size=32) }}
                </div>
                <div class="form-group">
                    {{ new_page_form.page_title.label }}
                    {{ new_page_form.page_title(class_="form-control", size=32) }}
                </div>
                <div class="form-group">
                    {{ new_page_form.content.label }}
                    {{ new_page_form.content(class_="form-control", size=32, rows=15) }}
                </div>
                {{ new_page_form.submit(class_="btn btn-primary") }}
                <a class="btn btn-secondary" href="{{url_for('wiki.view_page', page_id=new_page_form.id)}}"" role="
                    button"><i class="bi-x-circle"></i> Cancel</a>
            </form>

        </div>
    </div>
</div>
{% endblock content %}

waylon/templates/wiki/view.html
{% extends "layout.html" %}
{% block page_title %}
{{ title }}
{% endblock page_title %}

{% block content %}
<div class="container container-lg pt-3">
    <div class="row justify-content-center align-items-center g-2">
        <div class="col">
            <a name="" id="" class="btn btn-primary" href="{{url_for('wiki.page_list', page_id=page.id)}}" role="button"
                method="GET">
                <i class="bi-house"></i> Wiki
            </a>
            <a name="" id="" class="btn btn-primary" href="{{url_for('wiki.edit_page', page_id=page.id)}}" role="button"
                method="GET">
                <i class="bi-pencil"></i>
            </a>

            <!-- Button trigger modal -->
            <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
                <i class="bi-trash"></i>
            </button>
        </div>
    </div>
    <div class="row">
        <div class="col" style="margin-top: 10px;">
            <h1>{{page.page_title}}</h1>
        </div>
    </div>
    <div class="row" style="min-height: 100px;">
        <div class="col" style="margin-top: 10px;">
            {{html|safe}}
        </div>
    </div>
    <div class="row" style="margin-top: 10px;">
        <div class="col align-self-center"><small>Last Edited: {{page.last_edit.strftime("%Y-%m-%d %H:%M")}}</small>
        </div>
        <div class="col text-center align-self-center"><strong>{{page.page_name}}</strong></div>
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">Delete {{page.page_name}}</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                Are you sure you want to delete this page?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <a name="" id="" class="btn btn-primary" href="{{url_for('wiki.delete', page_id=page.id)}}"
                    role="button">
                    <button type="button" class="btn btn-primary">Delete</button>
                </a>
            </div>
        </div>
    </div>
</div>

{% endblock content %}