waylon/ipam/models.py
"""IPAM database models."""
import socket
import struct

from waylon.database import Column, CRUDMixin, PkModel, db


class IPAddress(PkModel, CRUDMixin):
    """An IP Address."""

    __tablename__ = "ip_addresses"

    ipv4_address = Column(db.String(15), unique=True, nullable=False)
    ipv4_cidr = Column(db.String(2), unique=True, nullable=False)
    device = Column(db.String(80), unique=True, nullable=False)
    location = Column(db.String(80), nullable=False)
    DHCP = Column(db.Boolean, default=False)
    MAC = Column(db.String(17), unique=True, nullable=True)

    def get_cidr(self):
        """Get CIDR."""
        cidr = f'{self.ipv4_address}/{self.ipv4_cidr}'
        return cidr

    def get_subnet(self):
        """Get netmask."""
        host_bits = 32 - int(self.ipv4_cidr)
        netmask = socket.inet_ntoa(struct.pack('!I', (1 << 32) - (1 << host_bits)))
        return netmask

    def __repr__(self):
        """Represent instance as a unique string."""
        return f"<IPAddress('{self.ipv4_address}/{self.ipv4_cidr}')>"

waylon/ipam/forms.py
"""IPAM forms."""
import re

from flask_wtf import FlaskForm
from wtforms import BooleanField, StringField, SubmitField
from wtforms.validators import DataRequired, Length, IPAddress


# TODO: add validators for IPv4 and CIDR

# def valididate_ipv4():
#     """Validate IPv4."""
#     message = "Invalid IPv4 address."

#     def _validate_ipv4(form, field):
#         """Validate IPv4."""
#         if not re.match(
#             "^(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$",
#             field.data,
#         ):
#             raise ValueError(message)


# def valididate_cidr():
#     """Validate CIDR."""
#     message = "Invalid CIDR."

#     def _validate_cidr(form, field):
#         """Validate CIDR."""
#         if not 1 <= int(field.data) <= 32:
#             raise ValueError(message)

#     return _validate_cidr


# def validate_mac():
#     """Validate MAC."""
#     message = "Invalid MAC. Must be in the format ab:cd:ef:12:34:56."

#     def _validate_mac(form, field):
#         """Validate MAC."""
#         if re.match("[0-9a-f]{2}([-:]?)[0-9a-f]{2}(\\1[0-9a-f]{2}){4}$", mac.lower()):
#             raise ValueError(message)

#     return _validate_mac


class IPAMForm(FlaskForm):
    """IPAM form."""

    ipv4_address = StringField(
        "IPv4 address", validators=[DataRequired(), Length(min=7, max=15), IPAddress()]
    )
    ipv4_cidr = StringField(
        "IPv4 CIDR", validators=[DataRequired(), Length(min=1, max=2)]
    )
    device = StringField("Device", validators=[DataRequired(), Length(min=1, max=80)])
    location = StringField(
        "Location", validators=[DataRequired(), Length(min=1, max=80)]
    )
    DHCP = BooleanField("DHCP")
    MAC = StringField("MAC", validators=[DataRequired(), Length(min=1, max=17)])
    submit = SubmitField("Submit")

waylon/ipam/__init__.py
""" IPAM initialization """

from . import forms, models, views

waylon/ipam/views.py
"""IPAM views."""

from flask import Blueprint, render_template, request, redirect, url_for, flash

from .forms import IPAMForm
from .models import IPAddress

blueprint = Blueprint("ipam", __name__, url_prefix="/ipam", static_folder="../static")

@blueprint.route("/")
def home():
    """Home page."""
    return redirect(url_for("ipam.ip_list"))

@blueprint.route("/list")
def ip_list():
    """IP Address page."""
    ip_addresses = IPAddress.query.all()
    return render_template("ipam/list.html", title="IP Address List", ip_addresses=ip_addresses)

@blueprint.route("/new", methods=["GET", "POST"])
def new():
    """New IP Address."""
    ip = IPAddress()
    form = IPAMForm()
    if request.method == "POST":
        if form.validate_on_submit():
            ip.ipv4_address = form.ipv4_address.data
            ip.ipv4_cidr = form.ipv4_cidr.data
            ip.device = form.device.data
            ip.location = form.location.data
            ip.DHCP = form.DHCP.data
            ip.MAC = form.MAC.data
            ip.save()
            flash("IP Address created.", "success")
            return redirect(url_for("ipam.view", ip_id=ip.id))
        else:
            return render_template("ipam/new.html", title="New IPAM Page", form=form, ip_address=ip)
    return render_template("ipam/new.html", title="New IPAM Page", ipam_form=form, ip_address=ip)

@blueprint.route("/edit", methods=["GET", "POST"])
def edit():
    """New IP Address."""
    ip_id = request.args.get("ip_id")
    ip = IPAddress.query.filter_by(id=ip_id).first()
    form = IPAMForm(obj=ip)
    if request.method == "POST":
        # if form.validate_on_submit(): # TODO: add validation
        ip.ipv4_address = form.ipv4_address.data
        ip.ipv4_cidr = form.ipv4_cidr.data
        ip.device = form.device.data
        ip.location = form.location.data
        ip.DHCP = form.DHCP.data
        ip.MAC = form.MAC.data
        ip.save()
        flash("IP Address updated.", "success")
        return redirect(url_for("ipam.view", ip_id=ip.id))
        # else:
        # return render_template("ipam/edit.html", title=f"Edit {ip.ipv4_address}", ipam_form=form, ip_address=ip)
    return render_template("ipam/edit.html", title=f"Edit {ip.ipv4_address}", ip_id=ip.id, ipam_form=form, ip_address=ip)

@blueprint.route("/view", methods=["GET"])
def view():
    """IP Address page."""
    ip_id = request.args.get("ip_id")
    ip = IPAddress.query.filter_by(id=ip_id).first()
    return render_template("ipam/view.html", title=f"IP Address {ip.ipv4_address}", ip_address=ip)
    

@blueprint.route("/delete")
def delete():
    """Delete IP Address."""
    ip_id = request.args.get("ip_id")
    ip = IPAddress.query.filter_by(id=ip_id).first()
    ip.delete()
    flash(f"IP Address {ip.ipv4_address} deleted.", "success")
    return redirect(url_for("ipam.ip_list"))

waylon/templates/ipam/edit.html
{% extends "layout.html" %}

{% block page_title %}{{ title }}{% endblock page_title %}

{% block content %}
    <div class="container-lg pt-3">
    <div class="row-cols-auto justify-content-center align-items-center g-2">
        <div class="col">
            <form action="" method="post">
                {{ ipam_form.hidden_tag() }}
                <div class="form-group">
                    {{ ipam_form.ipv4_address.label }}
                    {{ ipam_form.ipv4_address(class_="form-control", size=32) }}
                </div>
                <div class="form-group">
                    {{ ipam_form.ipv4_cidr.label }}
                    {{ ipam_form.ipv4_cidr(class_="form-control", size=32) }}
                </div>
                <div class="form-group">
                    {{ ipam_form.device.label }}
                    {{ ipam_form.device(class_="form-control", size=32) }}
                </div>
                <div class="form-group">
                    {{ ipam_form.location.label }}
                    {{ ipam_form.location(class_="form-control", size=32) }}
                </div>
                <div class="form-group">
                    {{ ipam_form.DHCP.label }}
                    {{ ipam_form.DHCP(class_="form-control form-check-input", type="checkbox", size=32) }}
                </div>
                <div class="form-group">
                    {{ ipam_form.MAC.label }}
                    {{ ipam_form.MAC(class_="form-control", size=32) }}
                </div>

                {{ ipam_form.submit(class_="btn btn-primary") }}
                <a class="btn btn-secondary" href="{{url_for('ipam.view', ip_id=ip_id)}}" role="button"><i class="bi-x-circle"></i> Cancel</a>
            </form>
        </div>
    </div>
</div>
{% endblock  %}

waylon/templates/ipam/list.html
{% extends "layout.html" %}

{% block page_title %}{{ title }}{% endblock page_title %}

{% block content %}
<div class="container pt-3">
    <div class="row justify-content-center align-items-center g-2">
        <div class="col">
            <a class="btn btn-primary" href="{{url_for('ipam.new')}}" role="button"><i class="bi-plus"></i> New</a>
        </div>
    </div>
    <div class="row justify-content-center align-items-center g-2">
        <div class="col">
            <div class="table-responsive-lg">
                <table class="table table-primary">
                    <thead>
                        <tr>
                            <th scope="col">IP Address</th>
                            <th scope="col">Device</th>
                            <th scope="col">Location</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for ip_address in ip_addresses %}
                        <tr class="">
                            <td scope="row"><a href="{{url_for('ipam.view', ip_id=ip_address.id)}}">{{ip_address.ipv4_address}}</a></td>
                            <td>{{ip_address.device}}</td>
                            <td>{{ip_address.location}}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

waylon/templates/ipam/new.html
{% extends "layout.html" %}

{% block page_title %}{{ title }}{% endblock page_title %}

{% block content %}
    <div class="container-lg pt-3">
    <div class="row-cols-auto justify-content-center align-items-center g-2">
        <div class="col">
            <form action="" method="post">
                {{ ipam_form.hidden_tag() }}
                <div class="form-group">
                    {{ ipam_form.ipv4_address.label }}
                    {{ ipam_form.ipv4_address(class_="form-control", size=32) }}
                </div>
                <div class="form-group">
                    {{ ipam_form.ipv4_cidr.label }}
                    {{ ipam_form.ipv4_cidr(class_="form-control", size=32) }}
                </div>
                <div class="form-group">
                    {{ ipam_form.device.label }}
                    {{ ipam_form.device(class_="form-control", size=32) }}
                </div>
                <div class="form-group">
                    {{ ipam_form.location.label }}
                    {{ ipam_form.location(class_="form-control", size=32) }}
                </div>
                <div class="form-group">
                    {{ ipam_form.DHCP.label }}
                    {{ ipam_form.DHCP(class_="form-control form-check-input", type="checkbox", size=32) }}
                </div>
                <div class="form-group">
                    {{ ipam_form.MAC.label }}
                    {{ ipam_form.MAC(class_="form-control", size=32) }}
                </div>

                {{ ipam_form.submit(class_="btn btn-primary") }}
                <a class="btn btn-secondary" href="{{url_for('ipam.view')}}" role="button"><i class="bi-x-circle"></i> Cancel</a>
            </form>
        </div>
    </div>
</div>
{% endblock  %}

waylon/templates/ipam/view.html
{% extends "layout.html" %}

{% block page_title %}{{ title }}{% endblock page_title %}

{% block content %}
<div class="container-lg pt-3">

    <div class="row justify-content-center align-items-center g-2">
        <div class="col">
            <a name="" id="" class="btn btn-primary" href="{{url_for('ipam.ip_list')}}" role="button"
                method="GET">
                <i class="bi-house"></i> IPAM
            </a>
            <a name="" id="" class="btn btn-primary" href="{{url_for('ipam.edit', ip_id=ip_address.id)}}" role="button"
                method="GET">
                <i class="bi-pencil"></i>
            </a>

            <!-- Button trigger modal -->
            <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
                <i class="bi-trash"></i>
            </button>
        </div>

    <div class="row justify-content-center align-items-center g-2">
        <div class="col-3 text-end fw-lighter">IPv4:</div>
        <div class="col">{{ip_address.ipv4_address}}/{{ip_address.ipv4_cidr}}</div>
    </div>
    <div class="row justify-content-center align-items-center g-2">
        <div class="col-3 text-end fw-lighter">Subnet:</div>
        <div class="col">{{ip_address.get_subnet()}}</div>
    </div>
    <div class="row justify-content-center align-items-center g-2">
        <div class="col-3 text-end fw-lighter">Device:</div>
        <div class="col">{{ip_address.device}}</div>
    </div>
    <div class="row justify-content-center align-items-center g-2">
        <div class="col-3 text-end fw-lighter">Location:</div>
        <div class="col">{{ip_address.location}}</div>
    </div>
    <div class="row justify-content-center align-items-center g-2">
        <div class="col-3 text-end fw-lighter">Static DHCP:</div>
        <div class="col">{{ip_address.DHCP}}</div>
    </div>
    <div class="row justify-content-center align-items-center g-2">
        <div class="col-3 text-end fw-lighter">MAC Address:</div>
        <div class="col">{{ip_address.MAC}}</div>
    </div>

</div>


<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">Delete {{ip_address.ipv4_address }}</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                Are you sure you want to delete this IP Address?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <a name="" id="" class="btn btn-primary" href="{{url_for('ipam.delete', ip_id=ip_address.id)}}"
                    role="button">
                    <button type="button" class="btn btn-primary">Delete</button>
                </a>
            </div>
        </div>
    </div>
</div>
{% endblock content %}